# This is the definition of API that conserve the state of variable received.
# By considering those API, the flow analysis will be much more accurate.
# All undocumented API return UNKNOWN state (considered unsafe).
#
# File format:
# <<<
# [Unique ID]:
#   namespace: [Namespace where the class is present]
#   className: [Class of the API]
#   member: ["method" => method call or "field" for assignment]
#   name: [Field name (assignment) or Method name (method call)]
#   argTypes: (Optional field) [Parameter types signature]
#   taintFromArguments: [Index of the argument that will influence the state of the return value.]
# <<<

#MemoryStream
MemoryStream_Constructor0:
  namespace: System.IO
  className: MemoryStream
  member: method
  name: .ctor
  argTypes: ()
  taintFromArguments: -1

#Directory
Directory_GetCurrentDirectory:
  namespace: System.IO
  className: Directory
  member: method
  name: GetCurrentDirectory
  argTypes: ()
  taintFromArguments: -1

#Path
Path_ChangeExtension:
  namespace: System.IO
  className: Path
  member: method
  name: ChangeExtension
  argTypes: (System.String, System.String)
  taintFromArguments: 0,1

Path_Combine2:
  namespace: System.IO
  className: Path
  member: method
  name: Combine
  argTypes: (System.String, System.String)
  taintFromArguments: 0,1

Path_Combine3:
  namespace: System.IO
  className: Path
  member: method
  name: Combine
  argTypes: (System.String, System.String, System.String)
  taintFromArguments: 0,1,2

Path_Combine4:
  namespace: System.IO
  className: Path
  member: method
  name: Combine
  argTypes: (System.String, System.String, System.String, System.String)
  taintFromArguments: 0,1,2,3

Path_CombineParamsString:
  namespace: System.IO
  className: Path
  member: method
  name: Combine
  argTypes: (params System.String[])
  taintFromArguments: 0

Path_GetDirectoryName:
  namespace: System.IO
  className: Path
  member: method
  name: GetDirectoryName
  argTypes: (System.String)
  taintFromArguments: 0

Path_GetExtension:
  namespace: System.IO
  className: Path
  member: method
  name: GetExtension
  argTypes: (System.String)
  taintFromArguments: 0

Path_GetFileName:
  namespace: System.IO
  className: Path
  member: method
  name: GetFileName
  argTypes: (System.String)
  taintFromArguments: 0

Path_GetFileNameWithoutExtension:
  namespace: System.IO
  className: Path
  member: method
  name: GetFileNameWithoutExtension
  argTypes: (System.String)
  taintFromArguments: 0

Path_GetFullPath:
  namespace: System.IO
  className: Path
  member: method
  name: GetFullPath
  argTypes: (System.String)
  taintFromArguments: 0

Path_GetInvalidFileNameChars:
  namespace: System.IO
  className: Path
  member: method
  name: GetInvalidFileNameChars
  argTypes: ()
  taintFromArguments: -1

Path_GetInvalidPathChars:
  namespace: System.IO
  className: Path
  member: method
  name: GetInvalidPathChars
  argTypes: ()
  taintFromArguments: -1

Path_GetPathRoot:
  namespace: System.IO
  className: Path
  member: method
  name: GetPathRoot
  argTypes: (System.String)
  taintFromArguments: 0

Path_GetRandomFileName:
  namespace: System.IO
  className: Path
  member: method
  name: GetRandomFileName
  argTypes: ()
  taintFromArguments: -1

Path_GetTempFileName:
  namespace: System.IO
  className: Path
  member: method
  name: GetTempFileName
  argTypes: ()
  taintFromArguments: -1

Path_GetTempPath:
  namespace: System.IO
  className: Path
  member: method
  name: GetTempPath
  argTypes: ()
  taintFromArguments: -1

Path_HasExtension:
  namespace: System.IO
  className: Path
  member: method
  name: HasExtension
  argTypes: (System.String)
  taintFromArguments: 0

Path_IsPathRooted:
  namespace: System.IO
  className: Path
  member: method
  name: IsPathRooted
  argTypes: (System.String)
  taintFromArguments: 0

#string constructors
#https://msdn.microsoft.com/en-us/library/system.string.string(v=vs.110).aspx
StringConstructor_1:
  namespace: System
  className: String
  member: method
  name: .ctor
  argTypes: (System.Char, System.Int32)
  taintFromArguments: 0,1

StringConstructor_2:
  namespace: System
  className: String
  member: method
  name: .ctor
  argTypes: (System.Char[])
  taintFromArguments: 0

StringConstructor_3:
  namespace: System
  className: String
  member: method
  name: .ctor
  argTypes: (System.Char[], System.Int32, System.Int32)
  taintFromArguments: 0

#String.Format
#https://msdn.microsoft.com/en-us/library/system.string.format(v=vs.110).aspx

StringFormat_1:
  namespace: System
  className: String
  member: method
  name: Format
  argTypes: (System.IFormatProvider, System.String, params System.Object[])
  taintFromArguments: 1,2

StringFormat_2:
  namespace: System
  className: String
  member: method
  name: Format
  argTypes: (System.IFormatProvider, System.String, System.Object)
  taintFromArguments: 1,2

StringFormat_3:
  namespace: System
  className: String
  member: method
  name: Format
  argTypes: (System.IFormatProvider, System.String, System.Object, System.Object)
  taintFromArguments: 1,2,3

StringFormat_4:
  namespace: System
  className: String
  member: method
  name: Format
  argTypes: (System.IFormatProvider, System.String, System.Object, System.Object, System.Object)
  taintFromArguments: 1,2,3,4

StringFormat_5:
  namespace: System
  className: String
  member: method
  name: Format
  argTypes: (System.String, params System.Object[])
  taintFromArguments: 0,1

StringFormat_6:
  namespace: System
  className: String
  member: method
  name: Format
  argTypes: (System.String, System.Object)
  taintFromArguments: 0,1

StringFormat_7:
  namespace: System
  className: String
  member: method
  name: Format
  argTypes: (System.String, System.Object, System.Object)
  taintFromArguments: 0,1,2

StringFormat_8:
  namespace: System
  className: String
  member: method
  name: Format
  argTypes: (System.String, System.Object, System.Object, System.Object)
  taintFromArguments: 0,1,2,3
