on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022

    env:
      Solution_Name: SecurityCodeScan.sln
      APPVEYOR_REPO_TAG_NAME: "${{github.event.inputs.version}}"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
        include-prerelease: false

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@ee4202680b63bd7b2f0deb71ab55104b71917843

    - name: Restore
      run: nuget restore $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Build
      run: msbuild -m $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Run Tests
      run: vstest.console.exe ./SecurityCodeScan.Test/bin/${{ matrix.configuration }}/SecurityCodeScan.Test.dll
        
    - name: Upload nuget package artifact
      uses: actions/upload-artifact@v2
      with:
        name: SecurityCodeScan.nupkg
        path: "./SecurityCodeScan/bin/${{ matrix.configuration }}/netstandard2.0/*.nupkg"
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        
    - name: Upload vsix artifact
      uses: actions/upload-artifact@v2
      with:
        name: SecurityCodeScan.vsix
        path: "./SecurityCodeScan.Vsix/bin/${{ matrix.configuration }}/*.vsix"
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    - name: Upload security-scan nuget tool artifact
      uses: actions/upload-artifact@v2
      with:
        name: security-scan.nupkg
        path: "./SecurityCodeScan.Tool/.NET Core/bin/${{ matrix.configuration }}/*.nupkg"
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        
    - name: Zip security-scan 4.x
      run: 7z a security-scan4x.zip "./SecurityCodeScan.Tool/.NET 4.x/bin/${{ matrix.configuration }}\net48/*"
        
    - name: Upload security-scan 4.x artifact
      uses: actions/upload-artifact@v2
      with:
        name: security-scan4x
        path: security-scan4x.zip
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        
    - name: Create draft release
      uses: softprops/action-gh-release@8a65c813553f4d05769635eb1b70180d25b9b61b
      with:
        draft: true
        name: ${{github.event.inputs.version}}
        fail_on_unmatched_files: true
        files: |
          ./SecurityCodeScan/bin/${{ matrix.configuration }}/**/*.nupkg
          ./SecurityCodeScan.Vsix/bin/${{ matrix.configuration }}/*.vsix
          ./SecurityCodeScan.Tool/.NET Core/bin/${{ matrix.configuration }}/*.nupkg
          security-scan4x.zip
