on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022

    env:
      Solution_Name: SecurityCodeScan.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
        include-prerelease: false

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore
      run: nuget restore $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Build
      run: msbuild -m $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Nuget tool
        path: "./SecurityCodeScan.Tool/.NET Core/bin/Release/*.nupkg"
