on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      configuration:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: windows-2022

    env:
      Solution_Name: SecurityCodeScan.sln
      APPVEYOR_REPO_TAG_NAME: "${{inputs.version}}"
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
        include-prerelease: false

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@ee4202680b63bd7b2f0deb71ab55104b71917843

    - name: Restore
      run: nuget restore $env:Solution_Name
      env:
        Configuration: ${{ inputs.configuration }}

    - name: Build
      run: msbuild -m $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ inputs.configuration }}
 
    - name: Run Tests
      run: vstest.console.exe ./SecurityCodeScan.Test/bin/${{ inputs.configuration }}/SecurityCodeScan.Test.dll

    - name: Publish
      if: ${{ inputs.publish }}
      uses: ./.github/actions/publish
      with: 
        version: ${{ inputs.version }}
        MARKETPLACE_TOKEN: ${{ inputs.MARKETPLACE_TOKEN }}
        NUGET_TOKEN: ${{ inputs.NUGET_TOKEN }}
