on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022

    env:
      Solution_Name: SecurityCodeScan.sln
      APPVEYOR_REPO_TAG_NAME: "${{github.event.inputs.version}}"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
        include-prerelease: false

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore
      run: nuget restore $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Build
      run: msbuild -m $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Upload nuget package artifact
      uses: actions/upload-artifact@v2
      with:
        name: SecurityCodeScan.nupkg
        path: "./SecurityCodeScan/bin/${{ matrix.configuration }}/**/*.nupkg"
        
    - name: Upload vsix artifact
      uses: actions/upload-artifact@v2
      with:
        name: SecurityCodeScan.vsix
        path: "./SecurityCodeScan.Vsix/bin/${{ matrix.configuration }}/*.vsix"

    - name: Upload security-scan nuget tool artifact
      uses: actions/upload-artifact@v2
      with:
        name: security-scan.nupkg
        path: "./SecurityCodeScan.Tool/.NET Core/bin/${{ matrix.configuration }}/*.nupkg"
        
    - name: Zip security-scan 4.x
      run: 7z a security-scan4x.zip "./SecurityCodeScan.Tool/.NET 4.x/bin/${{ matrix.configuration }}\net48/*"
        
    - name: Upload security-scan 4.x artifact
      uses: actions/upload-artifact@v2
      with:
        name: security-scan4x
        path: security-scan4x.zip
